### ISSUE TITLE
benchmarks_runner script does not exist

### ISSUE THREAD

**Issue by drvink** [janestreet/core_bench#12]
This package appears to be WIP/incomplete (a note in the README indicating this would have been nice), as there is no `benchmarks_runner` script anywhere to be found, despite the fact that a program linked with `-package core_bench.runner` produces this message upon being executed:

```
Uncaught exception:

  (Failure "Don't run directly, run using the benchmarks_runner script.")

Raised at file "pervasives.ml", line 32, characters 17-33
Called from file "inline_benchmarks_runner_lib_public/src/runner.ml", line 82, characters 13-83
Called from file "src/command.ml", line 2734, characters 6-97
Called from file "src/exn.ml", line 111, characters 6-10
```

As if this weren't already confusing enough, janestreet/ppx_bench@56fa338f56d8569cfa95602a7265de3b33f1ea2f seems to imply that a script exists *somewhere* (possibly intended to be the one that is not actually here)--but there was a lie from the beginning in the very first comment, in which reference is made to `pa_bench_sample`, presumably about a previous `camlp4` version of this benchmarking extension--so it was probably foolish to try to chase down which of umpteen repos might have contained the elusive `inline_benchmarks_runner`.

Additionally, setting `BENCHMARKS_RUNNER=TRUE` in one's environment in order to try to run the benchmarks without the script results in this:

```
arch-vm[1787]:~/hork/example% BENCHMARKS_RUNNER=TRUE ./sample
Warning: X_LIBRARY_INLINING is not set to true, benchmarks may be inaccurate.
Uncaught exception:

  (Failure
   "If you would like to run benchmarks, and are ok with getting inaccurate results due to lack of cross library inlining, use the -run-without-cross-library-inlining flag.")

Raised at file "pervasives.ml", line 32, characters 17-33
Called from file "inline_benchmarks_runner_lib_public/src/runner.ml", line 31, characters 2-69
Called from file "src/command.ml", line 2734, characters 6-97
Called from file "src/exn.ml", line 111, characters 6-10
```

Of course, one wild goose chase deserves another, so an investigation into `X_LIBRARY_INLINING` eventually leads to [janestreet/jenga](../../jenga), which appears to be _yet more_ build glop that may or may not induce some magic involving builds with [core_kernel](../../core_kernel), but if you expect the how or why here, either, to be documented, then I admire your unwavering optimism.

Presumably if the missing puzzle piece script existed, this would not happen:

```
arch-vm[1792]:~/hork/example% BENCHMARKS_RUNNER=TRUE ./sample -run-without-cross-library-inlining
Warning: X_LIBRARY_INLINING is not set to true, benchmarks may be inaccurate.
No benchmarks to run!
```

Please, guys--it's fine to make repos for stuff that's still undergoing alpha-stage development, but at least indicate somewhere that pieces are currently missing wholesale.

**Comment by aalekseyev** [comment]
The script was never in any repo as far as I know. We at Jane Street generate it by jenga. I don't know if jbuilder can do an equivalent thing.
This is an example file, it doesn't to very much:

    #!/bin/sh
    # This file was generated by jenga
    cd "$(dirname "$(readlink -f "$0")")"
    BENCHMARKS_RUNNER=TRUE BENCH_LIB=core_kernel BENCH_CONFIG_PATH=../../core_bench/inline_benchmarks_runner_lib_internal/etc/config.sexp exec ./inline_benchmarks_runner.exe "$@"

The check of `X_LIBRARY_INLINING` is just to make sure that we only benchmark binaries compiled with maximum optimization settings. This setting originates from Jane Street jenga rules and it might or might not be duplicated in jbuilder.
If you trust your compilation settings to be representative of how you compile production binaries, it's safe to ignore this warning.

**Comment by aalekseyev** [comment]
> No benchmarks to run!

And this error probably has nothing to do with either of X_LIBRARY_INLINING or the script. There might be an issue with how you compile the binary or with how you write benchmarks.

**Comment by drvink** [comment]
> The script was never in any repo as far as I know.

I see (and sorry for the frustration on my part). Thanks for the clarification about `X_LIBRARY_INLINING`. I don't see any references to `BENCH_CONFIG_PATH` in the [core_bench](..) source--is there something else that uses it, or is this variable used by some other internal/unrelated thing?

> There might be an issue with how you compile the binary or with how you write benchmarks.

Is there an example anywhere of how they should be written and compiled? As I said, it's not obvious if [ppx_bench](../../ppx_bench) is meant to be used with this or not.

**Comment by aalekseyev** [comment]
> BENCH_CONFIG_PATH

I think this is something internal/unrelated, yes. It should not be necessary.

> Is there an example ... it's not obvious

Ideally this would just be supported by your build system. Given that this issue exists: https://github.com/janestreet/jbuilder/issues/65, I guess it's not supported by jbuilder yet. Maybe you can gain some insight by following the discussion there.

Alternatively you could figure it out yourself. The key thing to watch out for is that [let%bench] definitions conditionally generate side-effectful code.

So you need to make sure that:
- condition is satisfied, whatever it is (appropriate flags given to the ppx extension, inappropriate are not)
- all the modules are linked in and not dropped from the final binary (maybe by "-linkall", but I can't see it used in our jenga rules so I'm not sure)

**Comment by diml** [comment]
I have a working example [here](https://github.com/diml/memory-access-bench). We are currently working on making inline benchmarks work smoothly with jbuilder: https://github.com/janestreet/jbuilder/pull/338

**Comment by drvink** [comment]
> Alternatively you could figure it out yourself.

Yes :) Given the number of moving parts involved, it wasn't clear whether all the needed pieces were public (i.e. whether it made more sense for me to keep digging through the code or whether something already existed internally).

> I have a working example here.

Great, this looks perfect. Thank you! I'll close this for now and reopen it if I notice anything else.

**Comment by vyorkin** [comment]
I've tried to do the same thing as in the example mentioned above (https://github.com/diml/memory-access-bench), but I still can't make it work :(
Here is what I'm doing: https://github.com/vyorkin/core_profiler_playground/blob/master/runner.sh
This is the output I'm getting by running the `./runner.sh` script:
```
Warning: X_LIBRARY_INLINING is not set to true, benchmarks may be inaccurate.
No benchmarks to run!
```

**Comment by aalekseyev** [comment]
@vyorkin, one suspicious thing I notice is that the library with benchmarks is called lib, and yet you call the benchmark runner with `~libname:"sample"`. I think those must match (or at least be in some relationship) because the benchmark runner filters the benchmarks by the library they're from.

**Comment by vyorkin** [comment]
Thanks! Yeah, sorry for that, I've updated the `libname` but still getting the same output (`No benchmarks to run`)

**Comment by aalekseyev** [comment]
I can get your example to work if I include something like this at the top of `bench/main.ml`:

```
module L = struct include Lib.Sample end
```
to force the module Sample to be linked in.

I'm not quite sure what's the right way of doing it though (maybe a well-placed -linkall flag can help).

**Comment by vyorkin** [comment]
@aalekseyev Thanks! Yeah, I've got it working by setting the `(link_flags -linkall)` to my executable stanza

**Comment by aalekseyev** [comment]
Note that the [example](https://github.com/diml/memory-access-bench/blob/master/dune) actually does have `(library_flags -linkall)` which we both missed.

**Comment by vyorkin** [comment]
Also (for others who may come here e.g. from google) here is another example of `ppx_bench` (in the `dune` itself): https://github.com/ocaml/dune/tree/master/bench
