### ISSUE TITLE
Meaning of units ?

### ISSUE THREAD

**Issue by hai-nguyen-van** [janestreet/core_bench#20]
I cannot find a documentation that explains the difference between `mWd`, `mjWd` and `Prom`. What do these units mean ?

**Comment by yminsky** [comment]
minor words, major words, promoted words, all per run.

**Comment by hai-nguyen-van** [comment]
Pardon my ignorance. What is a word ?

**Comment by yminsky** [comment]
A machine word, 64-bits on a 64-bit machine, 32-bits on a 32-bit machine.
