### ISSUE TITLE
Request: test with builtin # iterations

### ISSUE THREAD

**Issue by thelema** [janestreet/core_bench#8]
I have a function that already takes as input the # of iterations it will run, and I want to be able to use core_bench to do everything it currently does on that function instead of wrapping a unit function in a loop.

Specifically, I have a parsing automaton, and I want to measure the (average, etc.) cost of a transition, but i can't just run it on a single input character over and over, as this won't trigger any of the interesting characteristics.  I plan to run it for various number of transitions for testing purposes.

**Comment by ceastlund** [comment]
Well, this is an ancient issue. Sorry for the long wait.

I have bad news, and possibly good news. The bad news is, I don't think there's a straightforward way to do what you're asking in the actual code of core_bench. That would sort of fundamentally alter the way core_bench does its batching and measuring.

The good news is, we often run into this kind of thing internally, and there are some patterns we use for still getting a useful measurement. What I normally do in this case, is I write a loop like you have to measure transitions, and I set it to run a moderate number of iterations -- say 100. I then let core_bench measure that.

For regression purposes - to see what difference some change makes in your function - this suffices. Just benchmark the old version, and the new version, and divide the difference by 100 (or however many iterations you ran per batch).

If you want something closer to an absolute measure of cost, I'd then add another benchmark to measure the overhead of your loop. The overhead benchmark should perform the same loop, and the body should be simply `ignore (Sys.opaque_identity x)` for each variable `x` bound in the loop. Subtract the cost of the overhead benchmark from the cost of your loop benchmark, and that gives a reasonable approximation of the "true" cost of your transition function.

It's possible we should encode some pattern like this in core_bench more explicitly. I've never taken the time to work out what that would look like, though.

**Comment by thelema** [comment]
Thanks for the response, and thanks for trying to provide a workaround.
