### ISSUE TITLE
Request: Add ARM CPU support

### ISSUE THREAD

**Issue by mikegogulski** [janestreet/core_bench#9]
Currently, the bench_rdtsc() function in rdtsc_stubs.c is x86-specific. As I'm working on a project using Core_bench that targets both ARM and x86 (for now), being able to benchmark on ARM is important to me.

**Comment by ceastlund** [comment]
Sorry for the long, long wait, I see that this is an ancient request.

We don't support ARM and we don't have hardware to test it on. If you or anyone else are able to generate and test a patch, we'd be able to accept it.
